version: "3.9"

services:
  #checkouts:
  #  image: us-central1-docker.pkg.dev/miss-ann-proyecto/grupo-10/entrega2-checkouts:1.0
  #  container_name: checkouts
  #  environment:
  #    RACK_ENV: production
  #    MONOLITH_HOST: http://34.121.217.143
  #    AGENDA_HOST: agenda
  #    ORDERS_HOST: orders
  #    PAYMENTS_HOST: payments
  #    SELLERS_HOST: sellers
  #  ports:
  #    - "3010:3000"
  #  networks:
  #    - ecommerce-network

  agenda:
    image: ghcr.io/misw-4301-desarrollo-apps-en-la-nube/agenda-service-p2:0.1.0
    container_name: agenda
    ports:
      - "3020:3020"
    networks:
      - ecommerce-network

  orders:
    image: ghcr.io/misw-4301-desarrollo-apps-en-la-nube/orders-service-p2:0.1.0
    container_name: orders
    ports:
      - "3030:3020"
    networks:
      - ecommerce-network

  payments:
    image: ghcr.io/misw-4301-desarrollo-apps-en-la-nube/payments-service-p2:0.2.0
    container_name: payments
    ports:
      - "3040:3020"
    networks:
      - ecommerce-network

  sellers:
    image: ghcr.io/misw-4301-desarrollo-apps-en-la-nube/sellers-service-p2:0.1.0
    container_name: sellers
    ports:
      - "3050:3020"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
